FROM php:7.3-cli

ENV PATH="~/.composer/vendor/bin:./vendor/bin:${PATH}"

RUN mkdir -m 0777 /var/log/mg-prodcomp

# Install other missed extensions
RUN apt-get update \
    && apt-get install -y vim wget curl unzip mc libzip-dev libaio-dev \
    && docker-php-ext-install zip

# Install xDebug in case it's local developer's installation
RUN pecl install xdebug-2.7.0 \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_connect_back=off" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_host=xdebug" >> /usr/local/etc/php/conf.d/xdebug.ini

# Install composer
RUN  curl -sS https://getcomposer.org/installer | tee composer-setup.php \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer --1 \
    && rm composer-setup.php

# Copy files
COPY . /var/www/html
WORKDIR /var/www/html

RUN composer install --no-interaction --no-progress --no-ansi --no-dev --optimize-autoloader -vvv

CMD ["composer", "phpstan"]
